
âroot"_tf_keras_model*È{"name": "Koopman_AE_Model", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "Koopman_AE_Model", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 3]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 3]}, "float32", "input_1"]}, "keras_version": "2.6.0", "backend": "tensorflow", "model_config": {"class_name": "Koopman_AE_Model"}}2
Üroot.enc"_tf_keras_model*‡{"name": "encoder_model_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "EncoderModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 3]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 3]}, "float32", "input_1"]}, "keras_version": "2.6.0", "backend": "tensorflow", "model_config": {"class_name": "EncoderModel"}}2
èroot.koopman"_tf_keras_model*Â{"name": "koopman__model_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "Koopman_Model", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 16]}, "float32", "input_1"]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 16]}, "float32", "input_1"]}, "keras_version": "2.6.0", "backend": "tensorflow", "model_config": {"class_name": "Koopman_Model"}}2
§root.dec"_tf_keras_model*˛{"name": "decoder_model_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "DecoderModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 16]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [511, 16]}, "float32", null]}, {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [511, 16]}, "float32", null]}], {}]}, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [512, 16]}, "float32", "input_1"]}, "keras_version": "2.6.0", "backend": "tensorflow", "model_config": {"class_name": "DecoderModel"}}2
˜	root.enc.enc1"_tf_keras_layer*Ã{"name": "encoder_layer_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 3]}}2
¯
root.enc.enc2"_tf_keras_layer*Õ{"name": "encoder_layer_26", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 16]}}2
¯root.enc.enc3"_tf_keras_layer*Õ{"name": "encoder_layer_27", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 32]}}2
¯root.enc.enc4"_tf_keras_layer*Õ{"name": "encoder_layer_28", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 64]}}2
¯root.enc.enc5"_tf_keras_layer*Õ{"name": "encoder_layer_29", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "EncoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 32]}}2
˛root.koopman.koopman"_tf_keras_layer*Ã{"name": "koopman_layer_5", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "KoopmanLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 16]}}2
¯root.dec.dec1"_tf_keras_layer*Õ{"name": "decoder_layer_25", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "DecoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 16]}}2
¯root.dec.dec2"_tf_keras_layer*Õ{"name": "decoder_layer_26", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "DecoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 32]}}2
¯root.dec.dec3"_tf_keras_layer*Õ{"name": "decoder_layer_27", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "DecoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 64]}}2
¯root.dec.dec4"_tf_keras_layer*Õ{"name": "decoder_layer_28", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "DecoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 32]}}2
ˇroot.dec.outputLayer"_tf_keras_layer*Õ{"name": "decoder_layer_29", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "DecoderLayer", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [512, 16]}}2